\"\"\"AI camera configuration template — multi-camera, all local.\"\"\"
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AI_DIR = Path(__file__).resolve().parent
DATA_DIR = ROOT / "data"
FACES_DIR = ROOT / "faces"
WWW_DIR = ROOT / "www"
FFMPEG = ROOT / "tools" / "ffmpeg-master-latest-win64-gpl-shared" / "bin" / "ffmpeg.exe"

FACE_DB_PATH = DATA_DIR / "face_db.npz"
EVENTS_PATH = DATA_DIR / "events.jsonl"
UNKNOWN_DIR = DATA_DIR / "unknown"

# Multi-camera list template
CAMERAS = [
    {
        "id": "cam1",
        "name": "Kamera 1",
        "ip": "192.168.1.101",
        "rtsp": "rtsp://admin:PASSWORD@192.168.1.101:554/Streaming/Channels/102",
        "rtsp_sub": "rtsp://admin:PASSWORD@192.168.1.101:554/Streaming/Channels/102",
        "rtsp_main": "rtsp://admin:PASSWORD@192.168.1.101:554/Streaming/Channels/101",
        "brand": "hikvision",
    },
    {
        "id": "cam2",
        "name": "Kamera 2",
        "ip": "192.168.1.102",
        "rtsp": "rtsp://admin:PASSWORD@192.168.1.102:554/ch1/sub/av_stream",
        "rtsp_sub": "rtsp://admin:PASSWORD@192.168.1.102:554/ch1/sub/av_stream",
        "rtsp_main": "rtsp://admin:PASSWORD@192.168.1.102:554/ch1/main/av_stream",
        "brand": "oem",
    },
]

# Display / encode
DISPLAY_WIDTH_SUB = 960
DISPLAY_WIDTH_MAIN = 1280
JPEG_QUALITY_SUB = 78
JPEG_QUALITY_MAIN = 86
DISPLAY_WIDTH = DISPLAY_WIDTH_SUB
JPEG_QUALITY = JPEG_QUALITY_SUB

# AI (GPU — NVIDIA CUDA)
AI_WIDTH = 1280
YOLO_MODEL = "yolov8x.pt"
YOLO_IMGSZ = 960
YOLO_CONF = 0.45
YOLO_DEVICE = 0
YOLO_HALF = True
AI_FULL_ALL_CAMS = True
AI_BATCH_YOLO = True
AI_POST_WORKERS = 4
AI_PIPELINE = True
AI_FOCUS_REFINE = True
AI_FOCUS_IMGSZ = 1280
AI_BG_EVERY_N = 3

YOLO_CLASSES = ()
YOLO_CLASS_MIN_CONF = {
    "person": 0.35,
    "laptop": 0.60,
    "keyboard": 0.55,
    "mouse": 0.55,
    "remote": 0.55,
    "cell phone": 0.55,
    "book": 0.55,
    "tv": 0.55,
    "monitor": 0.55,
    "suitcase": 0.55,
    "handbag": 0.65,
    "backpack": 0.72,
    "chair": 0.35,
    "couch": 0.45,
    "dining table": 0.45,
    "bench": 0.50,
    "bottle": 0.50,
    "cup": 0.50,
    "bowl": 0.50,
}

YOLO_WIDE_CLASSES = ("laptop", "keyboard", "tv", "book", "remote")
YOLO_WIDE_MIN_ASPECT = 0.90
YOLO_TALL_FALSE_CLASSES = ("backpack", "handbag", "suitcase")
YOLO_TALL_MAX_ASPECT = 0.85
YOLO_TALL_MIN_CONF = 0.78

YOLO_LABELS_UZ = {
    "person": "odam",
    "bicycle": "velosiped",
    "car": "mashina",
    "motorcycle": "mototsikl",
    "chair": "stul",
    "tv": "televizor",
    "laptop": "noutbuk",
    "cell phone": "telefon",
}

FACE_MATCH_THRESHOLD = 0.36
FACE_SOFT_THRESHOLD = 0.28
FACE_MATCH_MARGIN = 0.05
FACE_MATCH_MARGIN_SOFT = 0.03
FACE_GALLERY_MAX_PROTOS = 16
FACE_ENROLL_MIN_QUALITY = 0.40
FACE_ENROLL_DUPLICATE_WARN = 0.82
FACE_DET_SIZE = (1600, 1600)
FACE_DET_THRESH = 0.40
FACE_EVERY_N = 1

FACE_MIN_DET_SCORE = 0.38
FACE_MIN_SIDE = 28
FACE_MIN_DISPLAY_SIDE = 40
FACE_MIN_BRIGHTNESS = 14.0
FACE_MIN_SHARPNESS = 5.0
FACE_REQUIRE_PERSON = False
FACE_CROP_MIN = 224
FACE_TEMPORAL_SEC = 2.5
FACE_TEMPORAL_TOP_K = 5
FACE_CONFIRM_HITS = 4
FACE_IDENTITY_HOLD_SEC = 90.0
FACE_ROOM_SESSION_ENABLED = True
FACE_ROOM_EMPTY_SEC = 180.0
FACE_ROOM_MATCH_IOU = 0.10
FACE_ROOM_MAX_OCCUPANTS = 8
FACE_SPATIAL_TTL_SEC = 12.0
FACE_SPATIAL_IOU_THRESH = 0.20
FACE_UNKNOWN_MIN_QUALITY = 0.55
FACE_USE_GPU = True
FACE_ENROLL_DET_SIZE = (640, 640)
FACE_ENROLL_DET_THRESH = 0.35

FACE_ANTISPOOF_ENABLED = True
FACE_ANTISPOOF_MODEL_DIR = DATA_DIR / "antispoof_models"
FACE_ANTISPOOF_REAL_THRESH = 0.55
FACE_ANTISPOOF_MOTION_BYPASS = 0.72
FACE_LIVENESS_ENABLED = True
FACE_LIVENESS_MIN_FRAMES = 4
FACE_LIVENESS_MIN_SEC = 0.45
FACE_LIVENESS_MOTION_THRESH = 0.08
FACE_LIVENESS_SOFT_THRESH = 0.035
FACE_LIVENESS_WINDOW_SEC = 3.5
FACE_LIVENESS_TRACK_MERGE_IOU = 0.22

UNKNOWN_COOLDOWN_SEC = 180.0
KNOWN_COOLDOWN_SEC = 15.0
UNKNOWN_MATCH_THRESHOLD = 0.38
UNKNOWN_SAVE_INTERVAL_SEC = 45.0
UNKNOWN_MAX_PHOTOS_PER_PERSON = 20
UNKNOWN_TTL_SEC = 2 * 3600
UNKNOWN_PURGE_INTERVAL_SEC = 60.0

HOST = "0.0.0.0"
PORT = 8080

AUTH_ENABLED = True
AUTH_USERNAME = "admin"
AUTH_PASSWORD = "CHANGE_ME_PASSWORD"
AUTH_SECRET = "CHANGE_ME_SECRET_KEY"

COLOR_KNOWN = (80, 200, 80)
COLOR_UNKNOWN = (60, 60, 230)
COLOR_SPOOF = (0, 140, 255)
COLOR_OBJECT = (220, 180, 60)
COLOR_PERSON_BOX = (200, 160, 40)
COLOR_FIGHT = (40, 40, 255)
COLOR_LITTER = (0, 165, 255)

FIGHT_ENABLED = True
FIGHT_BACKEND = "stgcn"
FIGHT_TRACKER = "bytetrack"
FIGHT_POSE_MODEL = "yolov8l-pose.pt"
FIGHT_POSE_IMGSZ = 960
FIGHT_POSE_HALF = True
FIGHT_SEQ_LEN = 48
FIGHT_ACTION_THRESH = 0.78
FIGHT_ACTION_DEVICE = 0
FIGHT_MIN_PEOPLE = 2
FIGHT_MIN_PERSON_CONF = 0.50
FIGHT_MAX_NORM_DIST = 0.85
FIGHT_MIN_IOU = 0.04
FIGHT_MAX_PAIR_IOU = 0.38
FIGHT_FLOW_THRESH = 3.8
FIGHT_JITTER_THRESH = 0.10
FIGHT_SCORE_THRESH = 0.80
FIGHT_CONFIRM_SEC = 1.6
FIGHT_HOLD_SEC = 2.5
FIGHT_COOLDOWN_SEC = 20.0
FIGHT_SCAN_ALL = True
FIGHT_REQUIRE_POSE = True
FIGHT_MIN_POSE_SCORE = 0.50
FIGHT_MIN_FLOW_SCORE = 0.55
FIGHT_MIN_INTRUSION = 0.22
FIGHT_SIDE_BY_SIDE_PENALTY = True
FIGHT_PAIR_MIN_LEN = 24

LITTER_ENABLED = True
LITTER_CLASSES = ("bottle", "cup", "bowl", "wine glass")
LITTER_MIN_CONF = 0.35
LITTER_MIN_PERSON_CONF = 0.35
LITTER_ASSOC_DIST = 1.35
LITTER_HAND_MAX_RATIO = 0.72
LITTER_GROUND_MIN_RATIO = 0.85
LITTER_GROUND_STILL_PX = 18.0
LITTER_GROUND_HOLD_SEC = 0.7
LITTER_CONFIRM_SEC = 1.0
LITTER_HOLD_SEC = 3.0
LITTER_COOLDOWN_SEC = 20.0
LITTER_SCORE_THRESH = 0.58
LITTER_SCAN_ALL = True
LITTER_REQUIRE_FLOOR = True
LITTER_FLOOR_RATIO = 0.68
LITTER_USE_POSE = True
LITTER_THROW_DROP_RATIO = 0.10
LITTER_THROW_WINDOW_SEC = 0.8
LITTER_THROW_MIN = 0.30
LITTER_FOCUS_EVERY_FRAME = True
LITTER_STATIC_ENABLED = True
LITTER_STATIC_REQUIRE_PERSON = False
LITTER_STATIC_FLOOR_RATIO = 0.70
LITTER_STATIC_MIN_CONF = 0.40
LITTER_STATIC_HOLD_SEC = 3.5
LITTER_STATIC_CONFIRM_SEC = 2.0
LITTER_STATIC_COOLDOWN_SEC = 45.0
LITTER_STATIC_SCORE_THRESH = 0.55
LITTER_STATIC_STILL_PX = 22.0
LITTER_STATIC_MIN_SIDE = 10
LITTER_STATIC_MAX_SIDE_FRAC = 0.22
